"use client";
import React from "react";
import { Box } from "@mui/material";

export default function HackingAnimation() {
  const hackingText = `
<div>
  <h1>Accessing...</h1>
  <p>Connecting to the mainframe...</p>
  <span>Decrypting files...</span>
</div>
<console>
  echo "data transmission in progress..."
  echo "loading system protocols..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  decrypting...
  echo "validating security protocols..."
  access_granted...
  echo "retrieving sensitive data..."
  in_progress...
  echo "encrypting outgoing messages..."
  encryption_successful...
  echo "scanning for vulnerabilities..."
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  echo "monitoring system activity..."
  activity_log_updated...
  echo "disconnecting from mainframe..."
  disconnected...
  echo "finalizing operations..."
  shutting_down...
  echo "data transmission in progress..."
  echo "loading system protocols..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  decrypting...
  echo "validating security protocols..."
  access_granted...
  echo "retrieving sensitive data..."
  in_progress...
  echo "encrypting outgoing messages..."
  encryption_successful...
  echo "scanning for vulnerabilities..."
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  echo "monitoring system activity..."
  activity_log_updated...
  echo "disconnecting from mainframe..."
  disconnected...
  echo "data transmission in progress..."
  echo "loading system protocols..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  decrypting...
  echo "validating security protocols..."
  access_granted...
  echo "retrieving sensitive data..."
  in_progress...
  echo "encrypting outgoing messages..."
  encryption_successful...
  echo "scanning for vulnerabilities..."
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  echo "monitoring system activity..."
  activity_log_updated...
  echo "disconnecting from mainframe..."
  disconnected...
  echo "finalizing operations..."
  shutting_down...
  echo "data transmission in progress..."
  echo "loading system protocols..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  decrypting...
  echo "validating security protocols..."
  access_granted...
  echo "retrieving sensitive data..."
  in_progress...
  echo "encrypting outgoing messages..."
  encryption_successful...
  echo "scanning for vulnerabilities..."
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  echo "monitoring system activity..."
  activity_log_updated...
  echo "disconnecting from mainframe..."
  disconnected...
  echo "finalizing operations..."
  shutting_down...
  echo "data transmission in progress..."
  echo "loading system protocols..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  decrypting...
  echo "validating security protocols..."
  access_granted...
  echo "retrieving sensitive data..."
  in_progress...
  echo "encrypting outgoing messages..."
  encryption_successful...
  echo "scanning for vulnerabilities..."
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  echo "monitoring system activity..."
  activity_log_updated...
  echo "disconnecting from mainframe..."
  disconnected...
  echo "finalizing operations..."
  shutting_down...
  echo "data transmission in progress..."
  echo "loading system protocols..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  echo "attempting bypass..."
  processing...
  echo "fetching encrypted data..."
  decrypting...
  echo "validating security protocols..."
  access_granted...
  echo "retrieving sensitive data..."
  in_progress...
  echo "encrypting outgoing messages..."
  encryption_successful...
  echo "scanning for vulnerabilities..."
  no_threats_detected...
  echo "uploading payload..."
  transfer_complete...
  echo "initiating cleanup..."
  logs_deleted...
  echo "system rebooting..."
  reboot_successful...
  echo "compiling code modules..."
  modules_ready...
  echo "activating AI sequence..."
  sequence_initiated...
  echo "querying external databases..."
  query_complete...
  echo "disabling external tracking..."
  stealth_mode_enabled...
  echo "monitoring system activity..."
  activity_log_updated...
  echo "disconnecting from mainframe..."
  disconnected...
  echo "finalizing operations..."
  shutting_down...
</console>
`;

  return (
    <Box
      sx={{
        width: "100%",
        height: "100%",
        backgroundColor: "#212529",
        color: "#228B22",
        fontFamily: "monospace",
        fontSize: "0.9rem",
        overflow: "hidden",
        position: "relative",
      }}
    >
      <Box
        sx={{
          position: "absolute",
          width: "100%",
          height: "200%",
          animation: "scroll 3s linear infinite",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Box component="div" sx={{ whiteSpace: "pre-line", lineHeight: "1.5" }}>
          {hackingText}
        </Box>
        <Box component="div" sx={{ whiteSpace: "pre-line", lineHeight: "1.5" }}>
          {hackingText}
        </Box>
      </Box>
      <style>{`
        @keyframes scroll {
          0% {
            transform: translateY(0);
          }
          100% {
            transform: translateY(-50%);
          }
        }
      `}</style>
    </Box>
  );
}
